### ISSUE TITLE
Rename to "rust_webpack_template"

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/deprecated_rust_wasm_template#10]
As discussed during the WG meeting today. We plan on having multiple different templates for various scenarios and tools.

Filing this issue as a "FCP"-style announcement for anyone who has any concerns to be able to voice them here before we go through with the renaming.

+cc @rustwasm/core

**Comment by sendilkumarn** [comment]
`rust_webpack_template` or `rust_web_template`

**Comment by fitzgen** [comment]
I think "rust_webpack_template" because of the reasons we talked about on call yesterday:

* Other templates and tools are also web-centric, so "rust_web_template" isn't really descriptive enough by itself.

* We don't want to be biased (whether only in appearance or otherwise) to particular tools outside the Rust ecosystem: we want to work well with everybody.
