### ISSUE TITLE
Webpack plugins

### ISSUE THREAD

**Issue by xtuc** [rustwasm/deprecated_rust_wasm_template#4]
wasm-bindgen could be used as a Webpack loader and the different manipulation to the wasm binary could be done using Webpack's plugins.

The configuration would look like that:

```js
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  }

  module: {
    rules: [
      {
        test: /\.rs$/,
        loader: "wasm-bindgen/loader",
        type: "webassembly/experimental"
      }
    ]
  },

  plugins: [
    new RustFinalizer({ /* config */ })
  ]

};
```

The user would import the Rust entry point: `import("./entry.rs").then(...)` and Webpack will run the toolchain and apply the according configuration (based on its env for example).

That will also enable watch rebuilds.

---

Currently it's unclear to me if wasm-bindgen needs to be a loader, maybe we could have a generic Rust loader and an additional wasm-bindgen plugin.

**Comment by fitzgen** [comment]
> The user would import the Rust entry point: import("./entry.rs").then(...) and Webpack will run the toolchain and apply the according configuration (based on its env for example).

Nitpick: We talked about this a little on the WG call yesterday, but I think we want to reference *crates* (or the `.wasm` file produced by compiling a crate) not rust source files. Nearly 100% of Rust development uses cargo to compile crates rather than compiling individual `.rs` files with `rustc`. The `.rs` file as an entry point is not the idiomatic paradigm for Rust programming.

**Comment by xtuc** [comment]
Yes, I remember about that. I had in mind that we could use an entrypoint with the JS API and pulling in all the deps.

Does it make sense to talk about an entrypoint in Rust world? The loader is a bonus IMO but we can definitely import the built wasm.

**Comment by fitzgen** [comment]
D'oh for some reason I didn't realize that @xtuc == sven >_<

> Does it make sense to talk about an entrypoint in Rust world?

I'm not super familiar with "entry points" in webpack, but my guess is that the equivalent in Rust is a crate. When you add a dependency on another Rust project, you add something like:

```rust
extern crate thing_we_are_depending_on;
```

**Comment by xtuc** [comment]
I have to admit that I don't have enough experience with Rust but I would use a file in my crate that defines an API that will be exposed to JS. That's what I called the entrypoint because that's the impression from JS. 

Also that will be used to trigger the compilation from a webpack loader, and as discussed using cargo.

**Comment by xtuc** [comment]
@fitzgen maybe it's not the best place but I've published `rust-plugin@0.0.4`. Do you want to setup `wasm-snip` here?

**Comment by fitzgen** [comment]
@xtuc sure! did you see #6? That has some discussion about *when* we want to `wasm-snip`.

**Comment by xtuc** [comment]
Update:
We should spawn `wasm-pack` instead of the individual binaries.
