### ISSUE TITLE
Pre-configure multiple different builds

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/deprecated_rust_wasm_template#6]
We should have a couple build pipelines/configurations from invoking `cargo` through serving locally with `webpack-dev-server`. I'm hazy on exactly how the webpack integration will look, but here are the three configurations I have typically had in wasm projects, and think we should support coming pre-configured out of the box in this template:

1. **debug**: Without optimizations and with debug info. This is fastest to build and has debug info. It is appropriate for development, testing, and debugging. Note, there is no need to run `wasm-opt` for this configuration. This is essentially:

  ```
  cargo build --target wasm32-unknown-unknown
  wasm-bindgen ...
  ``` 

2. **profiling**: A build with optimizations *and* debug info. This is slower to build than **debug**. It is appropriate for time profiling. This should enable LTO and run `wasm-opt` with the `-g` flag. This is essentially:

  ```
  cargo rustc -- -C debuginfo=2 -C opt-level=s -C lto=fat --target wasm32-unknown-unknown
  wasm-bindgen ...
  wasm-opt -g -Oz ...
  ```

3. **production**: A build with optimizations and without debug info in the final `wasm` artifact and snipping away debugging related code. Note that `wasm-snip` requires debug info, but we don't pass the `-g` flag to `wasm-opt` which causes the debug info to be removed from its output. This produces the smallest, fastest `wasm` binary.

  ```
  cargo rustc -- -C debuginfo=2 -C opt-level=s -C lto=fat --target wasm32-unknown-unknown
  wasm-bindgen ...
  wasm-snip --snip-rust-panicking-code --snip-rust-fmt-code ...
  wasm-opt -Oz ...
  ```

cc @sendilkumarn @xtuc since I expect a lot of this to end up as options to `rust-plugin`,

**Comment by xtuc** [comment]
That sounds great, I would suggest to align the mode with Webpack's env. `production`, in addition of optimizing the wasm binary, will minify the JavaScript.

From my point of view, it would be better to let Webpack control the build/pipeline/cargo. We just need to expose the options Rust devs are used to.

**Comment by sendilkumarn** [comment]
> From my point of view, it would be better to let Webpack control the build/pipeline/cargo. We just need to expose the options Rust devs are used to.

Exactly same thoughts. But added to that I want to have the everything in options, such that users can do zero to full configuration with this plugin

**Comment by V1shvesh** [comment]
Is anyone working on this? I'd like to help out if you'd have me.

**Comment by fitzgen** [comment]
@V1shvesh most of this work is/will be happening in https://github.com/rustwasm/wasm-pack/issues/153 right now
